"""empty message

Revision ID: 025652dc6fc5
Revises: 
Create Date: 2022-08-16 07:42:35.162891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025652dc6fc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True)) # Make nullabe True to allow creation of new column
    # ### end Alembic commands ###

    # Set values of new created completed column to True
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL')

    # Set nullable = False to force new inputs to have completed attribute
    op.alter_column('todos', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
