"""empty message

Revision ID: 434dbae2a248
Revises: f0742d09137a
Create Date: 2022-08-17 12:18:45.500371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434dbae2a248'
down_revision = 'f0742d09137a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
